# Generated by Django 5.2.10 on 2026-01-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, verbose_name='Название соревнования')),
                ('score', models.PositiveIntegerField(verbose_name='Место')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижениея',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('tg_username', models.CharField(max_length=63, verbose_name='Телеграм')),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игроки',
            },
        ),
    ]
