# Generated by Django 5.2.10 on 2026-01-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievment',
            options={'verbose_name': 'достижение', 'verbose_name_plural': 'достижения'},
        ),
        migrations.RenameField(
            model_name='achievment',
            old_name='score',
            new_name='rating',
        ),
    ]
