# Generated by Django 5.2.10 on 2026-01-28 22:01

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_achievment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='achievment',
            name='preview',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
