# Generated by Django 5.2.10 on 2026-01-28 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievment_description_achievment_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения'),
            preserve_default=False,
        ),
    ]
