# Generated by Django 5.2.10 on 2026-02-03 18:37

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievment',
            name='preview',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='images/default.png', null=True, upload_to='', verbose_name='Превью'),
        ),
    ]
