# Generated by Django 5.2.10 on 2026-02-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_achievment_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievment',
            name='preview',
        ),
        migrations.AddField(
            model_name='achievment',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на соревнование'),
        ),
    ]
