# Generated by Django 5.2.10 on 2026-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_achievment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.CharField(default='Стажер', max_length=255, verbose_name='Звание'),
        ),
    ]
